// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProtocolSite.API.Data;

#nullable disable

namespace ProtocolSite.API.Migrations
{
    [DbContext(typeof(ProtocolSiteDbContext))]
    partial class ProtocolSiteDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProtocolSite.API.Models.AuditEntry", b =>
                {
                    b.Property<long>("AuditEntryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AuditEntryID"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("ChangedByUserID")
                        .HasColumnType("bigint");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PrimaryKey")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("AuditEntryID");

                    b.HasIndex("ChangedAt");

                    b.HasIndex("EntityName");

                    b.ToTable("AuditEntries");
                });

            modelBuilder.Entity("ProtocolSite.API.Models.Protocol", b =>
                {
                    b.Property<long>("ProtocolID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ProtocolID"));

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("ProtocolID");

                    b.HasIndex("Phase");

                    b.HasIndex("Status");

                    b.ToTable("Protocols");
                });

            modelBuilder.Entity("ProtocolSite.API.Models.Site", b =>
                {
                    b.Property<long>("SiteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SiteID"));

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("SiteID");

                    b.HasIndex("Status");

                    b.ToTable("Sites");
                });

            modelBuilder.Entity("ProtocolSite.API.Models.SiteProtocol", b =>
                {
                    b.Property<long>("SiteProtocolID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SiteProtocolID"));

                    b.Property<DateTime?>("InitiationDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("InvestigatorID")
                        .HasColumnType("bigint");

                    b.Property<long>("ProtocolID")
                        .HasColumnType("bigint");

                    b.Property<long>("SiteID")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("SiteProtocolID");

                    b.HasIndex("InvestigatorID");

                    b.HasIndex("ProtocolID");

                    b.HasIndex("SiteID");

                    b.HasIndex("Status");

                    b.ToTable("SiteProtocols");
                });

            modelBuilder.Entity("ProtocolSite.API.Models.SiteProtocol", b =>
                {
                    b.HasOne("ProtocolSite.API.Models.Protocol", "Protocol")
                        .WithMany("SiteProtocols")
                        .HasForeignKey("ProtocolID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProtocolSite.API.Models.Site", "Site")
                        .WithMany("SiteProtocols")
                        .HasForeignKey("SiteID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Protocol");

                    b.Navigation("Site");
                });

            modelBuilder.Entity("ProtocolSite.API.Models.Protocol", b =>
                {
                    b.Navigation("SiteProtocols");
                });

            modelBuilder.Entity("ProtocolSite.API.Models.Site", b =>
                {
                    b.Navigation("SiteProtocols");
                });
#pragma warning restore 612, 618
        }
    }
}
